### ISSUE TITLE
Official Todo list. Pt. 001. Very high urgency

### ISSUE THREAD

**Issue by Robijnvogel** [DimensionalDevelopment/DimDoors#31]
[Full initial todo list](https://pastebin.com/WZhKE6zD).

- [ ] Finish destinations
	- [ ] Add a "ReturnDestination" according to [this](https://pastebin.com/UBP5m6Ab).
	- [ ] Make a consensus between [Runemoro's description](https://pastebin.com/dvT9Essh) and [Robijnvogel's description](https://pastebin.com/UBP5m6Ab)
	-  [ ] Add additional "composite destinations" for sending people somewhere based on several kinds of conditions.
	-  [ ] Add a library of pre-configured destinations, so that the same builder doesn't need to be used in-code and by players time and time again.
- [ ] Get Travis/Gradle to correctly incorporate the build number in the jar file name upon building the mod.
- [ ] Fix Entities turning invisible after traveling through DimDoors https://github.com/DimensionalDevelopment/DimDoors/issues/30
	- [ ] Chests as well.
- [ ] Fix Rift Tesseract Render speeding up if there's more than one in the player's view and/or when the player is looking at it from a different angle.
- [ ] Change the configuration format for Dungeon Pocket configuration
	- [ ] Add several "distribution types", such as "uniform", "gaussian" etc. These distribution types and their respective weights would determine the dungeon's weight (for the weighted random function that chooses the dungeon to be generated) at a specific depth.
- [ ] Repair Rift Connection Tool
	- [ ] Enable it to just make and disconnect a 1-directional link as well as paired links.
- [ ] Handle placement of Transient Doors structures in a later phase, to prevent CoFHWorld from replacing the door block with something else. CoFH World probably uses the oregen stage, by the way. See [this](https://pastebin.com/J1wwPqcs).
- [ ] Make Transient Portals a more general dimensional portal block that can have pretty much any shape
	- [ ] Make Portals (including DimDoors) only "open" and render if there's a "frame" of full blocks (isSideSolid should be enough, though) on all sides. Transient Portals could have some sort of detection algorithm for this (first search upwards, then in all directions, not only axis-aligned).
- [ ] Make portal render  2-sided, at least for the Transient Portal.
	- [ ] At least for Transient Doors.
	- [ ] Make the backside of DimDoors permanently solid, even if the door is open.

**Comment by Robijnvogel** [comment]
Added new bullet-point:
 - Change Crafting Recipes for Dimensional Doors to **require** Stable Fabric instead of just Ender Pearls.

**Comment by Robijnvogel** [comment]
Added new bullet-point:
- Make sure that all the Chest TileEntities are actually added to the TileEntity list per Schematic, so loot can be added in all Dungeon Pockets.

**Comment by Robijnvogel** [comment]
Added three new bullet-points:
- Repair Eternal Fabric's ability to teleport the player back to the Overworld
- Make Transient Portals close as they are entered by a player
- Lower the default Config value for generating Transient Portal structures

**Comment by Robijnvogel** [comment]
Added new bullet-point:
- Repair Monolith Spawn Eggs

**Comment by Robijnvogel** [comment]
Moved one bullet-point over from #32:
- Add an additional mods list to out schematic format:
	```
	1 list of the actual content being used of mods (blocks and (tile)entities)
		If these mods are not loaded, the schematic outright refuses to load
	1 list of all the mods that were loaded at the time of schematic creation (with versioning)
		If there are errors during loading of the schematic, the mods out of these that are lower versions or missing will be pointed out as suspects.```

Added seventeen bullet-points:
	- Add a config option to forcibly load Schematics from that have "required" mods that are not contained in the loaded-mods list. 
		- Perhaps even make it an integer between 0 and 2, to even have an option to not load schematics if they are in the "global" mod list and lacking.
- Rework the way that Rift-container Blocks, (door-)items and TileEntities are related. See [Pastebin](https://pastebin.com/Vyt35KGT)
	- Transient Portals collapsing to Rift Scars would have nothing to do with their destination. This should be Transient Portal `Block` functionality or still need a separate TileEntity extending the Rift of course.
- Change the Personal DimDoor and Chaos Door's Recipes to only need 1 door
- Change all Doors and the Transdimensional TrapDoor to drop exactly one normal Door/TrapDoor item upon breakage and never remove their Rift, not even in Creative.
- Add a creative item for Pocket Entrance Doors and Dungeon Doors for Dungeon Schematic Creation purposes.
- Add a _"Wrapper"_ Block, Entity, TileEntity etc. to the dimdev packages, to handle unavailable modded content upon schematic placement.
	- Which can contain any nbt.
	- and upon reading **from** NBT, can check if the mod is installed now and convert themselves to the original content if it **is** installed
	- Add a Wrapper Item, ~~which __links__ to an NBTTagCompound in a central, world-saved registry~~
		- ~~We may need to save Items-inside-Containers-inside-Schematics as their __resource location__ using a separate Item-palette~~ apparently this is terrible for performance, because reading from NBT is painfully inefficient.
		- Use item stack NBT, so an un-stackable item (otherwise, we'd have to register X instances for this, as we could only save 16 different Items per Item Wrapper variant. Item damage isn't optimal either)
			- Make it show the original item resource name, the stack size and the damage by default.
	- Make the Wrappers show some general information in Waila by default.
- Make Dungeons generate in the **middle** of their assigned grid "cell" and in the middle according to y-coord. This should make the player less likely to catch on fire when teleporting from a pocket to the Overworld/Nether/a modded dimension with Lava on the lower y-levels.
- Get the player's potion status and on-fire status before dimensional teleport and reset it after this is concluded

**Comment by Robijnvogel** [comment]
Added two new tasks:
- Make the configs comments more concrete and see if we can fix some stupid little things
- Make schematics not permanently load in RAM
