### ISSUE TITLE
Official todo-list. Pt. 002. High urgency

### ISSUE THREAD

**Issue by Robijnvogel** [DimensionalDevelopment/DimDoors#32]
[Full initial todo list](https://pastebin.com/WZhKE6zD).

- [ ] Add new registries for Warp doors and other doors and stuff 
	- [ ] make sure Chaos doors and Personal DimDoors don't get registered in the unlinked doors 
- [ ] Create an ItemRift (creative only), so we can register BlockRifts' TileEntityRifts correctly upon (creative) placementregistry
- [ ] Use a graph for the (linked) rift registry
- [ ] Rewrite Virtual Location displacement algorithm
	- [ ] Make sure Doors can never link to a depth lower than 0
	- [ ] Test what the best default config values would be
- [ ] Fix/finish Schematic conversion code 
	- [ ] Sign Tile Entities
	- [ ] Warp Doors and Warp Doors on Sandstone
	- [ ] That one Warp Door that is placed super low in the pocket and on Sandstone
- [ ] Make sponge schematic version and minimum required forge version automatically get updated from values in `build.gradle` or `gradle.config` `{$spongeSchematicVersion}`
- [ ] Move config file into the DimDoors config folder
	- [ ] edit config class to annotated config format.
	- [ ] move all the default config values and maximum and minimum values to a separate Constants class.
- [ ] Finish and/or repair `/saveschem` command
- [ ] Make sure no Transient Structures generate in/over water.

**Comment by Robijnvogel** [comment]
Added new bullet-point:
- Create and add textures for Coloured Ancient Fabric and enable those blocks.

**Comment by Robijnvogel** [comment]
Added new bullet-point:
- Add Bedrock or Ancient Fabrick under Limbo (or disable survival players destroying Unraveled Fabric)

**Comment by Robijnvogel** [comment]
Added three new bullet-points:
- Make the /pocket command work in/from all dimensions and add additional optional dimension- and position determining parameters to it.
- Give the entrance door a teleportdestination leading back to the "Overworld"?
- Add an additional mods list to out schematic format

**Comment by Robijnvogel** [comment]
Moved one bullet point to #31 : 
- Add an additional mods list to out schematic format

Added three bullet-points:
- Add a new destination type:` TempDestination`, which would be a composite destination that consists of two destinations. On first usage, the __first__ destination is used, after which the Rift changes its destination to the __second__ destination (and effectively tosses the first _temporary_ one.
- Schematic creation: a chest with one spawn egg stack in it in the top left slot, means that you want to spawn an entity of that type there.
- Rename the resource location of the DimDoors **Blocks** to "Quartz Dimensional Door" etc.

**Comment by Robijnvogel** [comment]
Added four new tasks:
- Add an extra optional argument to the saveschem command, that lets you add an array of additional mod ids that would be required to load the schematic. (Needed for advanced nested modded usage, with items within items or entities within items, etc.)
- Swap the names of Ancient and Eternal Fabric
- Make the mod not crash MC if the pocket config jsons point to a file path that doesn't exist
- Make beds in pocket dimensions and sleeping there possible (they are exploding like in the Nether right now)
