### ISSUE TITLE
Official todo-list. Pt. 003. Moderate urgency

### ISSUE THREAD

**Issue by Robijnvogel** [DimensionalDevelopment/DimDoors#33]
[Full initial todo list](https://pastebin.com/WZhKE6zD).

- [ ] If a Dimdoor is destroyed, either return the full DimDoor and remove the rift, or return the normal door and leave the rift behind.
	- [ ] The previous for Personal and Chaos doors and Transdimensional Trapdoors; The latter for Warp Doors and Iron and Golden DimDoors.
	- [ ] Make any normal door placeable on a rift.
	- [ ] Add dimdoor variants for all vanilla wooden doors. Not just oak.
- [ ] Make crafting component items be an `Item` instead of having a full-on separate class for them
- [ ] Make Eternal Fabric a liquid 
	- [ ] Without making it possible to pick up using a bucked in survival
	- [ ] Rename it, perhaps in the same fashion as Extra Utilities'
- [ ] Renaming some Items and Blocks, like RiftScar and TransDimensional Portals (instead of Doors)
- [ ] Retexture Rift Connection Tool
- [ ] Add Rift Scar Growth
- [ ] Split `PocketLib`/`ddutils` from the mod and make it a hard dependency
- [ ] Rift configuration GUI (on the rift connection tool)

Optional:
- [ ] Handle the relation between the Nether and virtual locations differently, because the Nether's coords relate to the Overworld coords in a 1:8 ratio.
- [ ] API for the mod
- [ ] Add Javadocs on methods. Everywhere. This is probably never going to be finished.

**Comment by Robijnvogel** [comment]
Added five new bullet-points:
- Make Chaos Doors distinguishable from Iron Dimdoors when placed
- Fix puzzle_wall (dungeon schematic)'s Minecart triggerer redstone system by adding an extra Minecart to the dispenser
- Set up some repo that people could contribute to.
- Write a guide on how to submit new Dungeon Schematics.
- Write a wiki on how to configure the weights of Dungeons being picked for generation at random.

**Comment by Robijnvogel** [comment]
Changed bullet-point:
- If a Dimdoor is destroyed, either return the full DimDoor and remove the rift, or return the normal door and leave the rift behind.
to
- If a Dimdoor is destroyed, always leave the rift behind and drop one normal Door.

Added five bullet-points:
- Add the ability to set biomes to certain x-y positions in a pocket (for creation of new Dungeons)
- Perm system: show warning when leaving the pocket into the void, before teleporting to Limbo
- Determine what happens if you put a Nether Portal in a Pocket and walk through
	- And implement it.
- Removing a Rift with a Rift Remover has a chance to drop some World Thread

Removed two bullet-points:
- ~"Make Chaos Doors distinguishable from Iron Dimdoors when placed"~ We are removing the Chaos Door **Block** for the moment. The Rift Destination should be handled by the Rift TileEntity exclusively.
- The previous for Personal and Chaos doors and Transdimensional Trapdoors; The latter for Warp Doors and Iron and Golden DimDoors.

**Comment by Robijnvogel** [comment]
- Add Wooden Dimdoors to the Nether Fortresses
- Fix gateways breaking up other structures such as villages
- Make gateway generation seed-based
	- Make sure that gateways don't generate overlapping
