### ISSUE TITLE
Official todo-list. Pt. 004. Low urgency

### ISSUE THREAD

**Issue by Robijnvogel** [DimensionalDevelopment/DimDoors#34]
[Full initial todo list](https://pastebin.com/WZhKE6zD).

- [ ] New render(s), fractal perhaps for the Rift Scar
- [ ] More Loot table configuration
	- [ ] World thread more likely to generate in a dungeon chest at all, but less of it per chest
	- [ ] New loot table for dispensers, filling them with arrows and/or random splash potions
	- [ ] Add world thread to the fishing loot table
- [ ] Make Dimdoors lockable so no-one can teleport "to" them
	- [ ] Make this effectively "close" the rift on the other side. Turning the other end(s) in a "stabilised" Rift-Scar in case of a Transient Portal or a DimDoor without a portal render and a solid back-plate in case of a Dimensional Door. Of course, this would mean that a Rift-Scar would be turned in a stabilised Rift-Scar when touched with a Rift Blade.
- [ ] Create .json files for the old pocket schematics
	- [ ] Nether Pockets only accessible from the nether
	- [ ] Test and add all Dungeon Pocket Schematics
	- [ ] Set correct schematic sizes
	- [ ] Balance the Pocket Schematics' weights
- [ ] Make a system for expanding or colouring private pocket by using world thread and dyes on the rift
- [ ] Transient Doors/Portals should also generate in other dimensions (configurable)
- [ ] Rewrite Teleportation to one central queue (PocketLib)
- [ ] Teleport history stack (PocketLib)
- [ ] Repair and turn on the permission managing system for between the dimensions and stuff (PocketLib?)
	- [ ] Add a block that a player can place in their pocket to allow other players to join, with a GUI for Pocket permissions and maybe even some sort of connection map.
	- [ ] Config option to dis-/allow other teleport methods for entering a Pocket for the first time
	- [ ] Make sure that opped players can teleport everywhere without repercussion
- [ ] Fire teleport/portal events on Forge/Sponge when teleporting
	- [ ] And listen to these kinds of events for compatibility with the permission managing system
- [ ] Admin item/command with GUI to view and manage all the pockets and their permissions
- [ ] Be able to look through DimDoors portals and rifts to see the other side. Render (LookingGlass)
- [ ] Make Portal Render work from other sides than just up, down and North, South, East and West. For possible implementation of future non-axis-alligned portal faces.
- [ ] Show Dungeon Titles when entering Pockets
- [ ] Add advancements that go with DimDoors actions like 
	- [ ] Entering a (personal) pocket for the first tim
	- [ ] Obtaining world-thread 
	- [ ] Crafting your first dimdoor
	- [ ] Visiting limbo, 
	- [ ] Succesfully closing a rift
	- [ ] etc.
- [ ] Music in dungeons
- [ ] Spherical Worlds (Pockets that wrap around. If a player exits at one side, they re-enter at the other side.)
- [ ] Add lore books to dungeon loot that describe various possible lores around DimDoors, Pockets, Limbo and the Monoliths and refer to other mods as well.

Optional:
- [ ] Add a Personal Pocket singularity https://github.com/Zixiken/DimDoors/issues/17
- [ ] It would be cool if there was a type of block that was immune to limbo, so you could build with it (there's always a guy that wants to live in the most ridiculous places)."
- [ ] Make monoliths drop something on death, since they can't be killed directly, so it's basically impossible without a TNT cannon.
- [ ] Shadow World? Something like the Nether <-> Overworld, but 1:1 instead of 1:8
- [ ] Perhaps make Limbo Coordinates correspond 1:8 or 8:1 (or a different ratio) to the Overworld?
- [ ] Door that generates pocket with a single door and a single fabric block for building
- [ ] You can throw world thread into the pocket entrance and it expands your pocket after you throw in enough
- [ ] Horizontally placed Dimdoors? Like... actual doors, but in the floors, ceilings and on their side in the wall.
- [ ] Some rail-rift for Mine Carts
- [ ] Dimensional support for other mods
	- [ ] Buildcraft Pipes
	- [ ] EnderIO Conduits
	- [ ] IC2 Cables
	- [ ] AE Cables
	- [ ] Mekanism Pipes
	- [ ] Thermal Dynamics Ducts
- [ ] Rift Glass: a block that is basically a glass-ish texture with the door rift rendered inside it
- [ ] Delete inaccessible pockets (recursively)
	- [ ] Destroying last destination rift in private/pocket shows dialog to confirm deletion of the pocket

**Comment by Robijnvogel** [comment]
Added two new bullet-points:
- Backport the mod to MC 1.10.2
- Backport the mod to MC 1.11.2

**Comment by Robijnvogel** [comment]
Added new bullet-point:
- Take a look at [these dungeons](https://github.com/cwbit/DimDoorsDungeons/tree/master/dungeons) and if applicable, include them in the mod.

**Comment by Robijnvogel** [comment]
Added ten new tasks:
- Add boolean config option `useCubicPocketPlacement` to, if Cubic Chunks is installed and a new world is created:
	- actually place the Dungeon Pockets on their `virtual_x = actual_x`, `depth = actual_y` and `virtual_x = actual_z` locations (with the cubic mid-point of the pocket) 
	- handle the `gridSize` config setting as a "minimum distance in x, y and z between the Pockets, that is prioritised over the minimum virtual distance of that other config setting.
	- a warning when opening a world which this is in, and Cubic Chunks is removed. Maybe even refuse to open it.
- Procedurally generated Dungeon Pockets (mazes? ask SenseiKiwi)
- Add advancements so the DimDoors recipes are added to the recipe book. (jsons, all of it, even rewrite the recipes to json. Use this tool: https://gist.github.com/williewillus/a1a899ce5b0f0ba099078d46ae3dae6e )
- Add a Music Disk for the Limbo sound
	- perhaps change the resource name accordingly?
- Add a "Music Block" that contantly plays some kind of user-defined sound?
	-  Add a system to load sound resources on-the fly for this block, perhaps even from a config folder. It should not have to be a resource pack, I think.
